### ISSUE TITLE
Add a custom arrangement   for sections

### ISSUE THREAD

**Issue by ktsyr1** [vangelov/devresume#4]
There is a problem, which is the inability to control each person's arrangement of sections according to priority

**Comment by vangelov** [comment]
Hello, I've just pushed a new version that will let you specify the sections order. There are more details in the schema panel at the bottom. Let me know if it works ok for you.

<img width="707" alt="Screenshot 2024-12-14 at 13 25 07" src="https://github.com/user-attachments/assets/cf5f6389-0281-4894-a0dd-0534aae5bc45" />
