### ISSUE TITLE
Scale content to page

### ISSUE THREAD

**Issue by saint-hilaire** [vangelov/devresume#6]
This is an awesome resume builder!

However, there's still one usability issue that is quite annoying.

If my content overflows the first page by only a little bit, I have a second page that is mostly empty. I cannot send such a resume out. The only solution now seems to be to very judiciously remove small pieces of content until it all fits. This is pretty cumbersome.

It would be be better if in such cases the text size is reduced a little bit, so everything still fits. Failing that, it would be good to be able to define page breaks, to avoid awkward page breaks in multi page resumes.

**Comment by vangelov** [comment]
Thank you, I'm glad you find it useful!

Reducing the size will make the text too hard to read. I'm thinking of allow the user to specify which sections should be forced to start on a new page. Would that work for you?

**Comment by saint-hilaire** [comment]
> Thank you, I'm glad you find it useful!
> 
> Reducing the size will make the text too hard to read. I'm thinking of allow the user to specify which sections should be forced to start on a new page. Would that work for you?

Hi, sounds like a great idea to me, many thanks

**Comment by vangelov** [comment]
I've pushed a new version that now supports this. There's a new setting in `meta` called `sectionsPageBreaks`

<img width="905" alt="Screenshot 2024-12-15 at 10 03 34" src="https://github.com/user-attachments/assets/4d6f0e24-c91b-4965-a603-c2f475241ee7" />
